### ISSUE TITLE
Caused by:     missing field `api_key` config.toml

### ISSUE THREAD

**Issue by TimmekHW** [capslock/stable-diffusion-bot#1]
i create 

api_key = "62------3:AAFNQuc3TA-----j8--LZTb8D--s"
allowed_users = [ list, of, telegram, ids ]
db_path = "./db.sqlite"
sd_api_url = "http://localhost:7860"
![image](https://user-images.githubusercontent.com/94626112/233859094-365d9ed1-de90-49fd-9681-0ff61940d1a9.png)

------  I edited for safety

**Comment by capslock** [comment]
Ensure that your `config.toml` is in the same directory that you're running the bot from. In your case, the path should be `C:\Users\Timmek\config.toml`.

**Comment by TimmekHW** [comment]
> Убедитесь, что вы `config.toml`находитесь в том же каталоге, из которого вы запускаете бота. В вашем случае путь должен быть `C:\Users\Timmek\config.toml`.

Convinced. he is there

**Comment by capslock** [comment]
How did you create the file? Is it listed when you type `ls config.toml`?

**Comment by TimmekHW** [comment]
config.toml

**Comment by capslock** [comment]
I don't have any more ideas; your configuration should work (actually, it should give you an error about `allowed_users` being invalid, but it doesn't even get that far).

In the future I may expand the CLI arguments to allow for a config file path to be provided, which may help with your issue.

If you want a potential alternative, you can try setting the arguments as env variables in powershell:

```
$Env:SD_TELEGRAM_API_KEY = "62------3:AAFNQuc3TA-----j8--LZTb8D--s"
$Env:SD_TELEGRAM_SD_API_URL = "http://localhost:7860/"
$Env:SD_TELEGRAM_ALLOWED_USERS = "[ list, of, telegram, ids ]"
$Env:SD_TELEGRAM_DB_PATH = "./db.sqlite"
stable-diffusion-bot
```
