### ISSUE TITLE
got picture from different users query

### ISSUE THREAD

**Issue by inqoperated** [capslock/stable-diffusion-bot#28]
i had one time occuring that i got the results from a friends query to my user and vice versa

**Comment by capslock** [comment]
This looks like an issue with `comfyui-api` reusing client id's. I hadn't tested this with multiple concurrent users before, but I implemented a fix in 97fa2f35cd52f64ecf7c2d5053d7516ce85c6af1 and it seems to fix things for me.

**Comment by capslock** [comment]
I'm assuming this is fixed with the above fix, please re-open if you still see it in the latest version.
