### ISSUE TITLE
How can I delete buttons and information that I don't need? 

### ISSUE THREAD

**Issue by TimmekHW** [capslock/stable-diffusion-bot#3]
![image](https://user-images.githubusercontent.com/94626112/234062702-52e81a1c-7db3-40f9-98f6-4632010544fd.png)

How can I delete buttons and information that I don't need? When I put /* code*/ the code is not compiled (

How can I painlessly remove the buttons / features of the bot?

**Comment by capslock** [comment]
It's currently not built to be that modular or easy to change, but making these changes should be pretty simple. You should be able to remove the buttons and extra text by changing `Response::send`: https://github.com/capslock/stable-diffusion-bot/blob/main/crates/stable-diffusion-bot/src/bot/handlers/image.rs#L87-L92

Deleting L90 should get rid of the keyboard.

The text is created with `MessageText`, e.g. https://github.com/capslock/stable-diffusion-bot/blob/main/crates/stable-diffusion-bot/src/bot/handlers/image.rs#L274

You can change that call to change the text. If you want it to just put the prompt text as the caption, you can change it to something like:

`let caption = MessageText::new(text.as_str());`

**Comment by TimmekHW** [comment]
is it possible to make the bot work only with "-gen" tags. And how to add Extract functionality to it?

**Comment by capslock** [comment]
Could you explain what those are? I don't know "-gen" tags or what Extract functionality is.

**Comment by TimmekHW** [comment]
> ionality is.

Suppose there is a group chat. By default, the bot responds to any message. Need command to call bot response

For example "-gen a girl, red hair, summer"

**Comment by capslock** [comment]
This is something that I planned to do so I just went ahead and did it here: https://github.com/capslock/stable-diffusion-bot/commit/cc9c27a33dc10083c987bf25f767fd3294618410

You can now use `/gen a watercolor of a corgi wearing a tophat` to generate images. If you enable bot privacy, then it won't see other messages in a group chat and will only respond to /slash commands.
