### ISSUE TITLE
How do I remove the buttons /img2img_setting and /text2img_setup?

### ISSUE THREAD

**Issue by TimmekHW** [capslock/stable-diffusion-bot#6]
![image](https://user-images.githubusercontent.com/94626112/234639228-681595da-5e86-4266-8e49-3b88521391be.png)

any deletion leads to non-compilation of the code

**Comment by capslock** [comment]
This is set by these lines: https://github.com/capslock/stable-diffusion-bot/blob/main/crates/stable-diffusion-bot/src/bot/mod.rs#L160-L165

If you want to remove all of the buttons, just delete all of those lines. If you want to just remove the settings buttons, those are L161.

**Comment by TimmekHW** [comment]
thx!
it's worked!
